#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod address;
pub mod context;
pub mod deploy_multi_send;
pub mod erc20;
pub mod ierc1155_errors;
pub mod ierc20;
pub mod ierc20_errors;
pub mod ierc20_metadata;
pub mod ierc20_permit;
pub mod ierc721_errors;
pub mod multi_send;
pub mod safe_erc20;
